### ISSUE TITLE
vdr is crashing on shutdown caused by vdr-plugin-graphlcd caused by graphlcd-base

### ISSUE THREAD

**Issue by pbiering** [M-Reimer/graphlcd-base#2]
backtrace

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	  return ret;
[Current thread is 1 (Thread 0x7f9944e807c0 (LWP 29208))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007f99453478a4 in __GI_abort () at abort.c:79
#2  0x00007f9945347789 in __assert_fail_base
    (fmt=0x7f992c01e583 "%s%s%s:%u: %s%sZusicherung \302\273%s\302\253 nicht erf\303\274llt.\n%n", assertion=0x7f99459f6096 "fcCacheChains[i] == NULL", file=0x7f99459f608c "fccache.c", line=807, function=<optimized out>) at assert.c:92
#3  0x00007f9945357026 in __GI___assert_fail
    (assertion=assertion@entry=0x7f99459f6096 "fcCacheChains[i] == NULL", file=file@entry=0x7f99459f608c "fccache.c", line=line@entry=807, function=function@entry=0x7f99459f6ef0 <__PRETTY_FUNCTION__.0> "FcCacheFini") at assert.c:101
#4  0x00007f99459cfabb in FcCacheFini () at fccache.c:807
#5  IA__FcFini () at fcinit.c:205
#6  0x00007f992f99d7b5 in GLCD::cSkinFont::~cSkinFont() (this=0x7f990c09b010, __in_chrg=<optimized out>) at font.c:31
#7  0x00007f992f99d898 in GLCD::cSkinFonts::~cSkinFonts() (this=0x7f990c0094a0, __in_chrg=<optimized out>) at font.c:223
#8  0x00007f992f9b5e3b in GLCD::cSkin::~cSkin() (this=0x7f990c009430, __in_chrg=<optimized out>) at skin.c:28
#9  0x00007f992fa13a87 in cGraphLCDDisplay::~cGraphLCDDisplay() (this=0x56260df70390, this=<optimized out>) at display.c:65
#10 0x00007f992fa1540f in cGraphLCDDisplay::~cGraphLCDDisplay() (this=0x56260df70390, this=<optimized out>) at display.c:61
#11 cPluginGraphLCD::DisconnectDisplay(unsigned int) (this=this@entry=0x56260e028e60, index=index@entry=0) at plugin.c:320
#12 0x00007f992fa19d08 in cPluginGraphLCD::~cPluginGraphLCD() (this=0x56260e028e60, this=<optimized out>) at plugin.c:124
#13 0x00007f992fa19e75 in cPluginGraphLCD::~cPluginGraphLCD() (this=0x56260e028e60, this=<optimized out>) at plugin.c:121
#14 VDRPluginDestroyer(cPluginGraphLCD*) (p=0x56260e028e60) at plugin.c:692
#15 0x000056260c7cb5b5 in cDll::~cDll() (this=0x56260df658e0, this=<optimized out>) at plugin.c:191
#16 cDll::~cDll() (this=0x56260df658e0, this=<optimized out>) at plugin.c:198
#17 0x000056260c7d62b2 in cListBase::Del(cListObject*, bool) (DeleteObject=true, Object=0x56260df658e0, this=<optimized out>) at tools.c:2209
#18 cPluginManager::Shutdown(bool) (this=0x7fff5eff0c30, Log=true) at plugin.c:524
#19 0x000056260c71f4d7 in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at vdr.c:1627
(gdb) 
```

related  code found in file: glcdskin/font.c

```cSkinFont::~cSkinFont(void) {
#ifdef HAVE_FONTCONFIG
    cSkinFont::FcInitCount --;
    if (cSkinFont::FcInitCount <= 0) {
      FcFini();   <--!!
    }
#endif
}
```

There are several hits found by Dr. Google related to that problem. Any hint how to fix? I can run test-builds if a patch is supplied.

**Comment by M-Reimer** [comment]
Can you try with only minimal amount of plugins? I wonder what would happen if other plugins are using fontconfig, too. Seems quite possible to get a race condition here.

**Comment by pbiering** [comment]
catched: graphlcd+skindesigner is causing core dump - but skindesigner is not using FcInit or FcFini directly

Crash is independent from order of start/stopping plugings - but 100% reproducable - how can the race condition between plugins be catched? There are statements found with Dr. Google that it could be better to drop call of FcFini in production code...only use FcPatternDestroy if required.

- https://stackoverflow.com/questions/26578993/whats-the-point-of-fcfini-in-the-fontconfig-library

**Comment by pbiering** [comment]
created local RPM with following patch, since then, no crash is happen anymore:

```
--- graphlcd-base/glcdskin/font.c.orig	2021-02-07 12:57:21.314788701 +0100
+++ graphlcd-base/glcdskin/font.c	2021-02-07 12:57:53.755433009 +0100
@@ -28,7 +28,7 @@
 #ifdef HAVE_FONTCONFIG
     cSkinFont::FcInitCount --;
     if (cSkinFont::FcInitCount <= 0) {
-      FcFini();
+      // FcFini(); // don't call to avoid crash because of race conditions e.g. with VDR plugin skindesigner
     }
 #endif
 }

```

**Comment by M-Reimer** [comment]
>  There are statements found with Dr. Google that it could be better to drop call of FcFini in production code...only use FcPatternDestroy if required.

Seems like this is the proper fix for this case. The problem here seems to be that fontconfig has a function oriented interface without objects. So once the fontconfig library is loaded into a process which may load external (unknown to the parent process) modules (e.g. plugins) then each plugin only knows its own usage of fontconfig while others may also use it. This means that this counter in graphlcd-base will only count usage inside graphlcd-base and not usage in other "plugins" (skindesigner, ...). If graphlcd-base now finds out that all internal references are gone, it calls "FcFini" while there may still be usage somewhere else.

I'm just wondering why it crashes with FcFini and not in any fontconfig usage after FcFini.

**Comment by M-Reimer** [comment]
This is where having VDR in a GIT repo really helps:

https://github.com/VDR4Arch/vdr/commit/8ce144c6078baf856fb82a96e7da2a725a06be5c

So VDR itself had this issue, too.

**Comment by M-Reimer** [comment]
Please give latest GIT version a try. If this is fine for you, then I'll mark a new release.

**Comment by pbiering** [comment]
working well, no longer core dumps found caused by graphlcd-base (have still hunt behind some others...)

**Comment by M-Reimer** [comment]
New release is out
